name: laporan_praktikum_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/6556dc6484a92.jpg
  - assets/Resep-Rujak-Cingur.jpg
  - assets/Praktis-dan-Simpel-Ini-Resep-Soto-Ayam-Lamongan-yang-Menggugah-Selera-.jpg.webp
  - assets/6274a029b12d7.jpg
  - assets/Ini-Cara-Membuat-Nasi-Pecel-Madiun-yang-Menggugah-Selera-.jpg.webp
  - assets/Resep-Sate-Ayam-Madura-Menu-Lezat-Khas-Indonesia-yang-Mendunia.jpg
  - assets/64d58bed6c722.jpeg
  - assets/6194ce2bf1647.jpeg
  - assets/tahu-campur.jpg
  - assets/383686148.webp